---
title: "Programas - SIGEF"
date: "30 de outubro de 2018"
output: 
  flexdashboard::flex_dashboard:
    orientation: column
    social: menu
    runtime: shiny

---

```{r global, include=FALSE}

library(leaflet)
library(readr)
library(flexdashboard)
library(highcharter)
library(dplyr)
library(viridisLite)
library(treemap)
library(dplyr)
library(arules)
library(data.table)
library(magrittr)

thm <- hc_theme(colors = c("#1a6ecc", "#434348", "#90ed7d"),
                chart = list(backgroundColor = "transparent",
                style = list(fontFamily = 'Source Sans Pro')),
                xAxis = list(gridLineWidth = 1))


extracao_cgaux <- read_delim("C:/Users/Rodrigo/Downloads/extracao_cgaux.csv",   ";", escape_double = FALSE, col_types = cols(NU_CNPJ = col_character(),         NU_PROCESSO = col_character()), locale = locale(encoding = "latin1"),     trim_ws = TRUE)

extracao_cgaux$ME_REFERENCIA <- as.Date(extracao_cgaux$ME_REFERENCIA, "%d/%m/%Y")

extracao_cgaux %<>% filter(ME_REFERENCIA >= "2013-01-01")

```


Relatório
=======================================================================

Inputs {.sidebar data-width=300}
-----------------------------------------------------------------------

```{r Sidebar}

# # Input Saldo
# selectInput(inputId = 'saldo', label = 'Selecione o Saldo a ser Visualisado no Mapa:', choices = c("VL_SALDO_CONTA", "VL_SALDO_FUNDOS","VL_SALDO_POUPANCA","VL_SALDO_RDB"), selected = "VL_SALDO_CONTA")
# 
#  escolha.saldo = reactive({
#    if (input$saldo=="VL_SALDO_CONTA"){
#    extracao_cgaux %>% select(code=SG_UF, value=VL_SALDO_CONTA)
#    } else if(input$saldo=="VL_SALDO_FUNDOS"){
#    extracao_cgaux %>% select(code=SG_UF, value=VL_SALDO_FUNDOS)
#    } else if(input$saldo=="VL_SALDO_POUPANCA"){
#    extracao_cgaux %>% select(code=SG_UF, value=VL_SALDO_POUPANCA)
#    } else{
#    extracao_cgaux %>% select(code=SG_UF, value=VL_SALDO_RDB)
#    }
#  })

# Input Estado

selectInput(inputId = 'UF', choices = sort(unique(extracao_cgaux$SG_UF)), label = 'Selecione o Estado:', selected = "Todos")

escolha.uf = reactive({
  
  if (input$UF=="Todos"){
  extracao_cgaux
  }else{
  extracao_cgaux %>% filter(SG_UF==input$UF)}
  
})

# Input Programa

renderUI({
  selectInput("Programa", label = "Selecione o Programa:",
        choices = unique(escolha.uf()$DS_PROGRAMA_FNDE))
  })

escolha.programa = reactive({
  
  escolha.uf() %>% filter(DS_PROGRAMA_FNDE==input$Programa)
  
})

```

Column {data-width=500}
-----------------------------------------------------------------------

### Saldo por Estado

```{r}

saldo_estados <- extracao_cgaux %>% 
          mutate(saldo_tot = VL_SALDO_CONTA + 
                             VL_SALDO_FUNDOS + 
                             VL_SALDO_POUPANCA + 
                             VL_SALDO_RDB) %>%
          group_by(SG_UF, ME_REFERENCIA) %>% 
          summarise(saldo_total = sum(saldo_tot)) %>%
          filter(ME_REFERENCIA == max(ME_REFERENCIA)) %>% 
          select(code=SG_UF, value=saldo_total)

n <- 4
colstops <- data.frame(
  q = 0:n/n,
  c = substring(viridis(n + 1), 0, 7)) %>%
  list_parse2()

renderHighchart({

hcmap("countries/br/br-all", data = saldo_estados, value = "value",
      joinBy = c("hc-a2", "code"),
      dataLabels = list(enabled = TRUE, format = '{point.code}'),
      tooltip = list(valuePrefix = "R$")) %>%
  hc_colorAxis(stops = colstops) %>%
  hc_legend(valueDecimals = 0, valueSuffix = "%") %>%
  hc_mapNavigation(enabled = TRUE) %>%
  hc_add_theme(thm)

})

```

### Saldo dos Fundos

```{r Render Graphics}

renderHighchart({

  escolha.programa() %>% group_by(ME_REFERENCIA) %>% summarise(total_saldo=sum(VL_SALDO_FUNDOS)) %>% select(total_saldo) %>% ts(start = 2013, end = c(2018, 9), frequency = 12) %>% hchart() %>% hc_add_theme(thm)
  
})

```


Column {.tabset data-width=500}
-----------------------------------------------------------------------

### Sales by Category

```{r, fig.keep='none'}
data("Groceries", package = "arules")
dfitems <- tbl_df(Groceries@itemInfo)

set.seed(10)

dfitemsg <- dfitems %>%
  mutate(category = gsub(" ", "-", level1),
         subcategory = gsub(" ", "-", level2)) %>%
  group_by(category, subcategory) %>% 
  summarise(sales = n() ^ 3 ) %>% 
  ungroup() %>% 
  sample_n(31)

tm <- treemap(dfitemsg, index = c("category", "subcategory"),
              vSize = "sales", vColor = "sales",
              type = "value", palette = rev(viridis(6)))

highchart() %>% 
  hc_add_series_treemap(tm, allowDrillToNode = TRUE,
                        layoutAlgorithm = "squarified") %>% 
  hc_add_theme(thm)
```

### Best Sellers

```{r}
# set.seed(2)
# 
# nprods <- 10
# 
# dfitems %>% 
#   sample_n(nprods) %>% 
#   .$labels %>% 
#   rep(times = sort(sample( 1e4:2e4, size = nprods), decreasing = TRUE)) %>% 
#   factor(levels = unique(.)) %>% 
#   hchart(showInLegend = FALSE, name = "Sales", pointWidth = 10) %>% 
#   hc_add_theme(thm) %>% 
#   hc_chart(type = "bar")

saldo_estados <- extracao_cgaux %>% mutate(saldo_tot = VL_SALDO_CONTA + 
                                                       VL_SALDO_FUNDOS + 
                                                       VL_SALDO_POUPANCA + 
                                                       VL_SALDO_RDB) %>%
group_by(SG_UF, ME_REFERENCIA) %>% 
summarise(saldo_total = sum(saldo_tot)) %>%
filter(ME_REFERENCIA == max(ME_REFERENCIA)) %>% 
select(code=SG_UF, value=saldo_total)

n <- 4
colstops <- data.frame(
  q = 0:n/n,
  c = substring(viridis(n + 1), 0, 7)) %>%
  list_parse2()

renderHighchart({

hcmap("countries/br/br-all", data = saldo_estados, value = "value",
      joinBy = c("hc-a2", "code"),
      dataLabels = list(enabled = TRUE, format = '{point.code}'),
      tooltip = list(valuePrefix = "R$")) %>%
  hc_colorAxis(stops = colstops) %>%
  hc_legend(valueDecimals = 0, valueSuffix = "%") %>%
  hc_mapNavigation(enabled = TRUE) %>%
  hc_add_theme(thm)

})
  
```


Mapa
=======================================================================

```{r}

leaflet() %>%
  addTiles() %>%
  addMarkers(lng= -47.9292, lat=-15.7801, popup="governo de Brasilia")

```


Tabela
=======================================================================

Inputs {.sidebar data-width=300}
-----------------------------------------------------------------------

```{r Sidebar2}

# Input Calendar

dateRangeInput(inputId="calendario", label="Selecione o Intervalo de Tempo", start = "2013-01-01", end = "2018-09-01", min = "2013-01-01",
  max = "2018-09-01", format = "yyyy-mm", startview = "year",
  weekstart = 0, language = "en", separator = " to ", width = NULL,
  autoclose = TRUE)

escolha.data_tbl = reactive({
  
  extracao_cgaux %>% filter(ME_REFERENCIA>=input$calendario[1] & ME_REFERENCIA <=input$calendario[2])
  
})

# Input Estado

renderUI({

  selectInput(inputId = 'uf_tbl', label = 'Selecione o Estado:', choices = sort(unique(escolha.data_tbl()$SG_UF)))

  })

escolha.uf_tbl = reactive({
  
  escolha.data_tbl() %>% filter(SG_UF==input$uf_tbl)
  
})

# Input Programa

renderUI({
  selectInput("programa_tbl", label = "Selecione o Programa:",
        choices = unique(escolha.uf_tbl()$DS_PROGRAMA_FNDE))
  })

escolha.programa_tbl = reactive({

  escolha.uf_tbl() %>% filter(DS_PROGRAMA_FNDE==input$programa_tbl)

})

```

Column
-----------------------------------------------------------------------
```{r}

renderTable({
  
  escolha.uf_tbl() %>% group_by(SG_UF, ME_REFERENCIA, DS_PROGRAMA_FNDE) %>% summarise(vl_saldo_conta=sum(VL_SALDO_CONTA), vl_saldo_fundos=sum(VL_SALDO_FUNDOS), vl_saldo_poupanca=sum(VL_SALDO_POUPANCA), vl_saldo_rdb=sum(VL_SALDO_RDB))
  
})
```